[build]
builder = "nixpacks"
buildCommand = "bash build.sh"

[deploy]
startCommand = "gunicorn evaluaciones_estudiantes.wsgi --log-file -"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
